[repository]
name = "kitconcept-website"
changelog = "CHANGELOG.md"
version = "version.txt"
container_images_prefix = "ghcr.io/kitconcept/kitconcept-website"
compose = ["docker-compose.yml"]

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend.package]
name = "kitconcept.website"
path = "backend"
code_path = "src/kitconcept/website"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "kitconcept.core"
publish = true

[frontend.package]
name = "@kitconcept/website"
path = "frontend/packages/kitconcept-website"
code_path = "src"
changelog = "frontend/packages/kitconcept-website/CHANGELOG.md"
towncrier_settings = "frontend/packages/kitconcept-website/towncrier.toml"
base_package = "@kitconcept/core"
publish = true
