[repository]
name = "kitconcept.website"
changelog = "CHANGELOG.md"
version = "version.txt"
compose = ["docker-compose.yml"]

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend.package]
name = "kitconcept.website"
path = "backend"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "kitconcept.core"
publish = true

[frontend.package]
name = "@kitconcept/website"
path = "frontend/packages/website"
changelog = "frontend/packages/website/CHANGELOG.md"
towncrier_settings = "frontend/packages/website/towncrier.toml"
base_package = "@kitconcept/core"
publish = true
