name: "kitconcept-website: Deploy"

on:
  workflow_call:
  workflow_dispatch:

jobs:

  config:
    name: "Config: Compute values used in workflow"
    uses: ./.github/workflows/config.yml

  deploy-dev:
    name: "Deploy: plone-site.kitconcept.dev"
    needs:
      - config
    if: ${{ needs.config.outputs.acceptance == 'true' || github.event_name == 'workflow_dispatch' }}
    uses: kitconcept/meta/.github/workflows/deploy.yml@main
    with:
        tag: ${{ github.ref_name }}
        environment: "plone-site.kitconcept.dev"
        stack-name: "plone-site-kitconcept-dev"
        stack-file: "devops/stacks/demo.yml"
        registry: "ghcr.io"
        username: ${{ github.actor }}
    secrets:
        password: ${{ secrets.GITHUB_TOKEN }}
        remote-host: ${{ secrets.DEPLOY_HOST }}
        remote-port: ${{ secrets.DEPLOY_PORT }}
        remote-user: ${{ secrets.DEPLOY_USER }}
        remote-private-key: ${{ secrets.DEPLOY_SSH }}
        env-file: |
            IMAGE_NAME_PREFIX=${{ needs.config.outputs.image-name-prefix }}
            IMAGE_TAG=${{ github.ref_name }}
            STACK_NAME=${{ vars.STACK_NAME }}
            STACK_PREFIX=${{ vars.STACK_PREFIX }}
            HOSTNAME=${{ vars.HOSTNAME }}
            CERTRESOLVER=${{ vars.CERTRESOLVER }}
            BASIC_AUTH_USER=${{ vars.BASIC_AUTH_USER }}
            BASIC_AUTH_PASSWORD=${{ vars.BASIC_AUTH_PASSWORD }}
    permissions:
        contents: read
        packages: write


  deploy-io:
    name: "Deploy: plone-site.kitconcept.io"
    needs:
      - config
    if: ${{ needs.config.outputs.acceptance == 'true' || github.event_name == 'workflow_dispatch' }}
    uses: kitconcept/meta/.github/workflows/deploy.yml@main
    with:
        tag: ${{ github.ref_name }}
        environment: "plone-site.kitconcept.io"
        stack-name: "plone-site-kitconcept-io"
        stack-file: "devops/stacks/persistent.yml"
        registry: "ghcr.io"
        username: ${{ github.actor }}
    secrets:
        password: ${{ secrets.GITHUB_TOKEN }}
        remote-host: ${{ secrets.DEPLOY_HOST }}
        remote-port: ${{ secrets.DEPLOY_PORT }}
        remote-user: ${{ secrets.DEPLOY_USER }}
        remote-private-key: ${{ secrets.DEPLOY_SSH }}
        env-file: |
            IMAGE_NAME_PREFIX=${{ needs.config.outputs.image-name-prefix }}
            IMAGE_TAG=${{ github.ref_name }}
            STACK_NAME=${{ vars.STACK_NAME }}
            STACK_PREFIX=${{ vars.STACK_PREFIX }}
            HOSTNAME=${{ vars.HOSTNAME }}
            CERTRESOLVER=${{ vars.CERTRESOLVER }}
            BASIC_AUTH_USER=${{ vars.BASIC_AUTH_USER }}
            BASIC_AUTH_PASSWORD=${{ vars.BASIC_AUTH_PASSWORD }}
    permissions:
        contents: read
        packages: write
