name: "kitconcept.website: CI"

on:
  push:
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/*.yml"
      - "devops/**"
      - "repository.toml"
  workflow_dispatch:

jobs:

  config:
    name: "Config: Compute values used in workflow"
    uses: ./.github/workflows/config.yml

  backend:
    uses: ./.github/workflows/backend.yml
    needs:
        - config
    with:
        base-tag: ${{ needs.config.outputs.base-tag }}
        image-name-prefix: ${{ needs.config.outputs.image-name-prefix }}
        image-name-suffix: backend
        python-version: ${{ needs.config.outputs.python-version }}
        kc-version: ${{ needs.config.outputs.kc-version }}
    if: ${{ needs.config.outputs.backend == 'true' }}
    permissions:
      contents: read
      packages: write

  frontend:
    uses: ./.github/workflows/frontend.yml
    needs:
        - config
    with:
        base-tag: ${{ needs.config.outputs.base-tag }}
        image-name-prefix: ${{ needs.config.outputs.image-name-prefix }}
        image-name-suffix: frontend
        node-version: ${{ needs.config.outputs.node-version }}
        volto-version: ${{ needs.config.outputs.volto-version }}
    if: ${{ needs.config.outputs.frontend == 'true' }}
    permissions:
      contents: read
      packages: write

  frontend-addon-versions:
    uses: ./.github/workflows/frontend-addon-versions.yml
    needs:
        - config
    with:
        node-version: ${{ needs.config.outputs.node-version }}
        volto-version: ${{ needs.config.outputs.volto-version }}
    if: ${{ needs.config.outputs.frontend == 'true' }}
    permissions:
      contents: read
      packages: write

  deploy-dev:
    name: "Deploy: plone-website.kitconcept.dev"
    needs:
        - config
        - frontend
        - frontend-addon-versions
        - backend
    if: ${{ always() && needs.config.outputs.acceptance == 'true' && github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && !contains(needs.*.result, 'failure') }}
    uses: kitconcept/meta/.github/workflows/deploy.yml@main
    with:
        tag: ${{ github.ref_name }}
        environment: "plone-website.kitconcept.dev"
        stack-name: "plone-website-kitconcept-dev"
        stack-file: "devops/stacks/demo.yml"
        registry: "ghcr.io"
        username: ${{ github.actor }}
    secrets:
        password: ${{ secrets.GITHUB_TOKEN }}
        remote-host: ${{ secrets.DEPLOY_HOST }}
        remote-port: ${{ secrets.DEPLOY_PORT }}
        remote-user: ${{ secrets.DEPLOY_USER }}
        remote-private-key: ${{ secrets.DEPLOY_SSH }}
        env-file: |
            IMAGE_NAME_PREFIX=${{ needs.config.outputs.image-name-prefix }}
            IMAGE_TAG=${{ github.ref_name }}
            STACK_NAME=${{ vars.STACK_NAME }}
            STACK_PREFIX=${{ vars.STACK_PREFIX }}
            HOSTNAME=${{ vars.HOSTNAME }}
            CERTRESOLVER=${{ vars.CERTRESOLVER }}
            BASIC_AUTH_USER=${{ vars.BASIC_AUTH_USER }}
            BASIC_AUTH_PASSWORD=${{ vars.BASIC_AUTH_PASSWORD }}
    permissions:
        contents: read
        packages: write

  deploy-io:
    name: "Deploy: plone-website.kitconcept.io"
    needs:
        - config
        - frontend
        - frontend-addon-versions
        - backend
    if: ${{ always() && needs.config.outputs.acceptance == 'true' && github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && !contains(needs.*.result, 'failure') }}
    uses: kitconcept/meta/.github/workflows/deploy.yml@main
    with:
        tag: ${{ github.ref_name }}
        environment: "plone-website.kitconcept.io"
        stack-name: "plone-website-kitconcept-io"
        stack-file: "devops/stacks/persistent.yml"
        registry: "ghcr.io"
        username: ${{ github.actor }}
    secrets:
        password: ${{ secrets.GITHUB_TOKEN }}
        remote-host: ${{ secrets.DEPLOY_HOST }}
        remote-port: ${{ secrets.DEPLOY_PORT }}
        remote-user: ${{ secrets.DEPLOY_USER }}
        remote-private-key: ${{ secrets.DEPLOY_SSH }}
        env-file: |
            IMAGE_NAME_PREFIX=${{ needs.config.outputs.image-name-prefix }}
            IMAGE_TAG=${{ github.ref_name }}
            STACK_NAME=${{ vars.STACK_NAME }}
            STACK_PREFIX=${{ vars.STACK_PREFIX }}
            HOSTNAME=${{ vars.HOSTNAME }}
            CERTRESOLVER=${{ vars.CERTRESOLVER }}
            BASIC_AUTH_USER=${{ vars.BASIC_AUTH_USER }}
            BASIC_AUTH_PASSWORD=${{ vars.BASIC_AUTH_PASSWORD }}
    permissions:
        contents: read
        packages: write
